server:
  port: 9088

spring:
  application:
    name: config-service
  profiles:
    active: git,dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hyuk-s-ecommerce-msa-project/ecommerce-config-repository
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - info
          - busrefresh

---
# [dev 설정 섹션 - 로컬 인텔리제이용]
spring:
  config:
    activate:
      on-profile: dev

encrypt:
  key-store:
    location: file:./app/apiEncryptionKey.jks
    password: ${KEYSTORE_PASSWORD}
    alias: apiEncryptionKey
    secret: ${KEY_PASSWORD}

rabbitmq:
  host: localhost
  port: 5672

---
# [prod 설정 섹션 - Azure 배포용]
spring:
  config:
    activate:
      on-profile: prod

encrypt:
  key-store:
    location: file:/app/apiEncryptionKey.jks # 리눅스 컨테이너 내부 절대 경로
    password: ${KEYSTORE_PASSWORD}
    alias: apiEncryptionKey
    secret: ${KEY_PASSWORD}

rabbitmq:
  host: rabbitmq-devops # 도커 네트워크 내부 이름
  port: 5672